name: Publishing

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install and build
        run: |
          npm ci
          npm run lint
          npm run docs
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs

